### ISSUE TITLE
При нулевой скорости игры, игра не останавливается

### ISSUE THREAD

**Issue by ermakof** [artem-volirvag/otus-react#16]
Действия пользователя:
1. Пользователь авторизуется в приложении
2. Устанавливает скорость игры равной нулю
3. Сохраняет настройки
4. Нажимает на кнопку Старт

ОР: кнопка старт неактивна или движения в игре нет
ФР: кнопка старт активна движение в игре есть

Нужно либо дизаблить кнопку старт, если скорость равна нулю, либо установить минимальное значение скорости не равное нулю либо выводить сообщение пользователю что игра не будет работать при настройке скорости равной нулю.

**Comment by artem-volirvag** [comment]
спасибо
