### ISSUE TITLE
Частота обновления поля не соответствует настройке скорости

### ISSUE THREAD

**Issue by centralToNowhere** [artem-volirvag/otus-react#20]
Действия для воспроизведения:

1. Перейти https://artem-volirvag.github.io/otus-react/#/login
2. Ввести имя пользователя
3. Установить значение скорости 1
4. Нажать кнопку применить
5. Нажать кнопку старт
6. Сделать двойной клик по кнопке Пауза/Возобновить во время задержки обновления поля
![Peek 2022-02-28 18-26](https://user-images.githubusercontent.com/18603013/155986719-fd9891a2-50e6-4361-8acb-9e2f442b79e9.gif)

Ожидаемое поведение: обновления поля во всех случаях проходят равномерно, с установленной в настройках задержкой
Фактическое поведение: обновления поля в некоторых случаях проходят  неравномерно, со случайной задержкой

Возможное решение - в саге делать `fork` игрового цикла, сохранять `Task` этого форка, и отменять его, когда происходит событие `pause`
```
export function* gameLoop() {
  while(true) {
    const app: State = yield select(selectApp);
    yield put(appActions.setCellsData(nextGeneration(app.cellsData)));
    yield delay(speedToMs(app.settings.speed));
  }
}

export function* playGame() {
  const task: Task = yield fork(gameLoop);
  yield take(appActions.pause.type);
  yield cancel(task);
}
```

**Comment by artem-volirvag** [comment]
спасибо
